# Encoding Categorical Data #

# Ordinal Encoding Techniques #

In [54]:
import pandas as pd
import numpy as np
from pygame.transform import threshold
from statsmodels.nonparametric.kdetools import counts

In [55]:
df = pd.read_csv('customer.csv')
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [56]:
df = df.iloc[:,2:]

In [57]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [59]:
X_train

     review education
4   Average        UG
34  Average    School
37  Average        PG
17     Poor        UG
30  Average        UG
42     Good        PG
2      Good        PG
28     Poor    School
41     Good        PG
23     Good    School
3      Good        PG
16     Poor        UG
49     Good        UG
48     Good        UG
11     Good        UG
19     Poor        PG
36     Good        UG
26     Poor        PG
13  Average    School
24  Average        PG
38     Good    School
31     Poor    School
5   Average    School
15     Poor        UG
20  Average    School
22     Poor        PG
32  Average        UG
21  Average        PG
46     Poor        PG
47     Good        PG
29  Average        UG
6      Good    School
25     Good    School
44  Average        UG
45     Poor        PG
40     Good    School
9      Good        UG
8   Average        UG
18     Good    School
12     Poor    School

In [60]:
from sklearn.preprocessing import OrdinalEncoder

In [61]:
oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [62]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [63]:
X_train= oe.transform(X_train)
X_test= oe.transform(X_test)

In [64]:
X_train

array([[1., 1.],
       [1., 0.],
       [1., 2.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.]])

In [65]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [66]:
from sklearn.preprocessing import LabelEncoder

In [67]:
le =LabelEncoder()

In [68]:
le.fit(Y_train)

LabelEncoder()

In [69]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [70]:
Y_train= le.transform(Y_train)
Y_test= le.transform(Y_test)

In [71]:
Y_train

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [72]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# One Hot Encoding Techniques #

In [73]:
df_1=pd.read_csv('car.csv')

In [74]:
df_1.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [75]:
df_1['owner'].value_counts()

owner
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: count, dtype: int64

# 1. One Hot Encoding using Pandas #

In [76]:
pd.get_dummies(df_1,columns=['fuel','owner'])

,name,year,selling_price,km_driven,seller_type,transmission,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti 800 AC,2007,60000,70000,Individual,Manual,False,False,False,False,True,True,False,False,False,False
1,Maruti Wagon R LXI Minor,2007,135000,50000,Individual,Manual,False,False,False,False,True,True,False,False,False,False
2,Hyundai Verna 1.6 SX,2012,600000,100000,Individual,Manual,False,True,False,False,False,True,False,False,False,False
3,Datsun RediGO T Option,2017,250000,46000,Individual,Manual,False,False,False,False,True,True,False,False,False,False
4,Honda Amaze VX i-DTEC,2014,450000,141000,Individual,Manual,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Individual,Manual,False,True,False,False,False,False,False,True,False,False
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Individual,Manual,False,True,False,False,False,False,False,True,False,False
4337,Maruti 800 AC BSIII,2009,110000,83000,Individual,Manual,False,False,False,False,True,False,False,True,False,False
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Individual,Manual,False,True,False,False,False,True,False,False,False,False
4339,Renault KWID RXT,2016,225000,40000,Individual,Manual,False,False,False,False,True,True,False,False,False,False

# N-1 One Hot Encoding #

In [77]:
pd.get_dummies(df_1,columns=['fuel','owner'],drop_first=True)

,name,year,selling_price,km_driven,seller_type,transmission,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti 800 AC,2007,60000,70000,Individual,Manual,False,False,False,True,False,False,False,False
1,Maruti Wagon R LXI Minor,2007,135000,50000,Individual,Manual,False,False,False,True,False,False,False,False
2,Hyundai Verna 1.6 SX,2012,600000,100000,Individual,Manual,True,False,False,False,False,False,False,False
3,Datsun RediGO T Option,2017,250000,46000,Individual,Manual,False,False,False,True,False,False,False,False
4,Honda Amaze VX i-DTEC,2014,450000,141000,Individual,Manual,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Individual,Manual,True,False,False,False,False,True,False,False
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Individual,Manual,True,False,False,False,False,True,False,False
4337,Maruti 800 AC BSIII,2009,110000,83000,Individual,Manual,False,False,False,True,False,True,False,False
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Individual,Manual,True,False,False,False,False,False,False,False
4339,Renault KWID RXT,2016,225000,40000,Individual,Manual,False,False,False,True,False,False,False,False

# One Hot Encoding Sklearn #

In [105]:
from sklearn.model_selection import train_test_split
# Select both columns explicitly using a list of column names
X = df_1.iloc[:,0:8]
Y = df_1.iloc[:, -1] # This is correct for grabbing the last column (owner)

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [106]:
df_1.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [107]:
from sklearn.preprocessing import OneHotEncoder

In [114]:
ohe = OneHotEncoder(drop='first')

In [115]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [116]:
x_test_new = ohe.fit_transform(x_test[['fuel','owner']]).toarray()

In [118]:
np.hstack((x_train[['name','km_driven']].values,x_train_new))

array([['Mahindra Scorpio S11 BSIV', 20000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti Swift Dzire VDI', 50000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti Alto 800 LXI', 25000, 0.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Maruti Ciaz VDi Plus SHVS', 51000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti Ertiga VDI', 80000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai Santro Xing GL Plus', 80000, 0.0, ..., 0.0, 0.0, 0.0]],
      shape=(3472, 10), dtype=object)

# One Hot emcoding with Top Categories #

In [122]:
counts = df_1['name'].value_counts()

In [123]:
counts.nunique()
threshold = 30

In [125]:
repl = counts[counts <= threshold].index

In [126]:
pd.get_dummies(df_1['name'].replace(repl, 'uncommon'))

,Hyundai EON Era Plus,Maruti Alto 800 LXI,Maruti Alto LX,Maruti Alto LXi,Maruti Swift Dzire VDI,uncommon
0,False,False,False,False,False,True
1,False,False,False,False,False,True
2,False,False,False,False,False,True
3,False,False,False,False,False,True
4,False,False,False,False,False,True
...,...,...,...,...,...,...
4335,False,False,False,False,False,True
4336,False,False,False,False,False,True
4337,False,False,False,False,False,True
4338,False,False,False,False,False,True
4339,False,False,False,False,False,True