In [29]:
import mysql.connector
import pandas as pd

conn=mysql.connector.connect(host='localhost',user='root',password='arpan123@',database='world')

In [30]:
df = pd.read_sql_query('SELECT * FROM city',conn)

C:\Users\mukhe\AppData\Local\Temp\ipykernel_17072\1019285517.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('SELECT * FROM city',conn)

In [31]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [32]:
df.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [36]:
import requests

response= requests.get('https://covid-19-data.p.rapidapi.com/country/code?format=json&code=it')

In [37]:
response.json()

{'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'}

In [40]:
pd.DataFrame(response.json()['results']).head()

KeyError: 'results'

##Web sracping##

In [43]:
from bs4 import BeautifulSoup

In [50]:
webpage=requests.get('https://www.kaggle.com/datasets/busielmorley/worldcities-pop-lang-rank-sql-create-tbls').text

In [51]:
soup=BeautifulSoup(webpage,'lxml')

In [52]:
soup.find_all('h1')[0].text

IndexError: list index out of range

In [53]:
for i in soup.find_all('h2'):
  print(i.text.strip())